// globals.d.ts
declare module "*.css";
declare module "*.scss";
declare module "*.sass";
declare module '@radix-ui/react-dropdown-menu';
declare module 'react-hook-form';
declare module '@radix-ui/react-tooltip';
declare module 'vaul';
declare module '@radix-ui/react-tabs';
declare module '@radix-ui/react-navigation-menu';
declare module '@radix-ui/react-accordion';
declare module 'react-day-picker';
declare module 'react-hook-form';
declare module  '@radix-ui/react-separator';
declare module '@radix-ui/react-scroll-area'
declare module '@radix-ui/react-select';
declare module '@radix-ui/react-radio-group';
declare module 'react-resizable-panels';
declare module '@radix-ui/react-context-menu';
declare module '@radix-ui/react-avatar';
declare module 'recharts';
declare module '@radix-ui/react-checkbox'
declare module 'embla-carousel-react';
declare module 'input-otp';
declare module '@radix-ui/react-menubar'
declare module '@radix-ui/react-popover'
declare module '@radix-ui/react-slider'
declare module 'next-themes';
declare module '@radix-ui/react-switch'
declare module '@radix-ui/react-toggle'
declare module '@radix-ui/react-toggle-group'
declare module '@radix-ui/react-label'